### ISSUE TITLE
Video tutorial and nodejs

### ISSUE THREAD

**Issue by StrangerGithuber** [soketi/soketi#325]
Hello
I am not that smart in websocket topic yet. Studying nowadays this topic. I found this github from laravel echo server and it looks promising.
I tried the documentation and the serverside works however configuration side is not that perfect. What I mean, I found this https://docs.soketi.app/getting-started/environment-variables and it mentions this: https://github.com/soketi/soketi/blob/master/src/options.ts . Ok, but it would be nice if there would be a full example configuration and if someone wants to delete some parts then they could. Because it can be confusing.

Is there a video tutorial which explains and give in example much as possible everything about soketi, laravel?

I am planning to use this with laravel of course plus with nodejs client. Is it enough to use pusher-client library at nodejs side or I need something else too?

Sorry for the beginner questions. No idea where I can ask these stuffs. Thank you in advance the answers.

**Comment by tizis** [comment]
nodejs + laravel 

Also you need configured supervisor for socket' processes watching.

There nothing hard, but a lot of pitfalls.

For example, if you used laravel valet as development environment in ssl mode — you would have a problem with ws connecting. 
Or, you would have a problem with client's echojs config, just because wrong client config — is broken ws connection without any error codes.

**Comment by tizis** [comment]
And, if you using cloudflare and want run ws server on specific port of main site domain — just don't do it, use subdomain instead if this.

**Comment by rennokki** [comment]
See codecourse's course: https://codecourse.com/courses/soketi-basics
