### ISSUE TITLE
Pusher Client uses SockJS and XHR polling when the connection fails

### ISSUE THREAD

**Issue by elbojoloco** [soketi/soketi#408]
When using the recommended pusher-js client library to connect to your Soketi server and at some point the connection is timed out or closed (by the client it seems), the pusher-js library will ignore the configured host and infinitely try to reconnect to official pusher hosts until you refresh the page. An example url looks like: `https://sockjs-mt1.pusher.com/pusher/app/app-key/793/34vlfh0e/xhr_streaming?protocol=7&client=js&version=7.0.3&t=1646658213555&n=17`

Is there a known or recommended way to force pusher-js to use your configured host for retries? My client side config looks like this (using laravel-echo with pusher driver):

```
new Echo({
    broadcaster: "pusher",
    key: "app-key",
    cluster: "mt1",
    forceTLS: true,
    wsHost: "ws.myserver.io",
});
```

**Comment by lawrencedudley** [comment]
I can't promise this is a fix but @Daynnnnn is giving this a go:

`// Only use WebSockets
const pusher = new Pusher(APP_KEY, {
  cluster: APP_CLUSTER,
  enabledTransports: ['ws', 'wss'],
  disabledTransports: ['xhr_streaming']
});`

**Comment by elbojoloco** [comment]
> I can't promise this is a fix but @Daynnnnn is giving this a go:
> 
> ```
> // Only use WebSockets
> const pusher = new Pusher(APP_KEY, {
>   cluster: APP_CLUSTER,
>   enabledTransports: ['ws', 'wss'],
>   disabledTransports: ['xhr_streaming']
> });
> ```

Will give this a try. Although it seems that that should just disable the reconnect all together, whereas ideally we would want it to reconnect to our own websocket host.

**Comment by aryanjaya** [comment]
When using pusher-js, pusher will handle unsuccessful connection by trying to start connection with WebSockets, wait a moment and then try an HTTP fallback in parallel ([see details](https://blog.pusher.com/how-we-built-pusher20-part-1/)) ([see their implementation](https://blog.pusher.com/how-we-built-pusher-js-2-0-part-2-implementation/)). Pusher will use url endpoint from `httpHost` configuration during HTTP fallback. Since you didn't specify the `httpsHost` configuration, pusher will use its default configuration ([see here](https://github.com/pusher/pusher-js/blob/91459e12053d0362e6356e27800a0f2fcab52f5e/src/core/config.ts#L87)).

To solve your problem (for the meantime), you can tell pusher-js to only use WebSocket connection by set `enabledTransports` configuration ([docs](https://github.com/pusher/pusher-js#enabledtransports-array)).

In the end, your code will look like this.:
```
new Echo({
    broadcaster: "pusher",
    key: "app-key",
    cluster: "mt1",
    enabledTransports: ['ws', 'wss'],
    forceTLS: true,
    wsHost: "ws.myserver.io",
});
```

It might be better if the Soketi server added a feature to establish a connection using an Http connection like Pusher did.

**Comment by elbojoloco** [comment]
@lawrencedudley @aryanjaya your fix for setting `enabledTransports` works perfectly! @rennokki is it a good addition for the docs maybe?

**Comment by rennokki** [comment]
Based on [Pusher JS's docs](https://github.com/pusher/pusher-js#disabledtransports-array), I can see that `disabledTransports` _overwrites transports whitelisted via the `enabledTransports` options._

I'm assuming the right configuration would be:

```js
new Echo({
    broadcaster: 'pusher',
    key: 'your-app-key',
    disabledTransports: ['xhr_streaming', 'xhr_polling', 'sockjs'],
    forceTLS: true,
    wsHost: 'ws.myserver.io',
});
```

The only problem is: _This is a whitelist, so any new transports we introduce in the future will be used until you explicitly add them to this list._ Basically, future Pusher JS versions will need the `disabledTransports` to be changed again.

I see that docs' examples are having `enabledTransports` set. Should I change it to the above example's `disabledTransports` instead?

**Comment by lawrencedudley** [comment]
Ah it's not mine, it's @Daynnnnn's! I'm just the messenger.

We do still have some reconnect bits to debug our side - definitely interested in seeing whether Pusher is more reliable using xhr. It feels like it's there for a reason.

**Comment by rennokki** [comment]
@lawrencedudley However, as the web evolved, XHR is another protocol that resembles nowadays' WebSockets. A lot of browsers support WebSockets, so the concern to implement XHR should be really small.

The fallback happens because of Pusher's logic: it believes that it does not support WebSockets once the WebSocket connection falls. Setting `enabledTransports: ['ws', 'wss']` without `disabledTransports` should work right away. If this is the issue, it definitely is another underlying problem, possibly the browser or the server itself. Sometimes when I test the Soketi locally and I close it, the test connection fails and it falls back to XHR.

**Comment by elbojoloco** [comment]
I haven't had my issue since adding `enabledTransports: ['ws', 'wss']` and not using `disabledTransports`.

**Comment by rennokki** [comment]
It seems like the docs are containing the `enabledTransports`. Please let me know if the issues are solved with the fix mentioned by @elbojoloco
