### ISSUE TITLE
how to use soketi without laravel-echo?

### ISSUE THREAD

**Issue by gwachhamit** [soketi/soketi#771]
without laravel-echo, how can we connect to socket?
I am trying to connect via firecamp and like `ws://localhost:6001/` but it says 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/11870771/210062259-f95bda60-c13a-4f8c-8c41-bf5096f98cbe.png">

**Comment by wjstraver** [comment]
yes, you can connect without laravel-echo. I would recommend you to use pusherjs at least as library to connect, since soketi is build on the pusher protocol.

If you want to connect without any library, you must connect to a url looking something like the following:

`ws://localhost:6001/app/[app_key]?protocol=7&client=js&version=7.2.0&flash=false`

Note that the pusher protocol requires sending a Ping signal every 30 seconds (`{"event":"pusher:ping","data":{}}`) otherwise the server might disconnect

**Comment by stayallive** [comment]
Soketi is not an all-purpose websocket server and is specifically designed to adhere to the Pusher protocol. You can read a little about that [here](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/). Generaly it is advised to use any of the Pusher [client libraries](https://pusher.com/docs/channels/channels_libraries/libraries/#client-libraries), however if you can't use any of them you are a little in uncharted territory but I hope one of the resources helps figuring it out!
